from tkinter import *
welcome=Tk()
welcome.title("HEENA BUILD CALCULATER")
welcome.geometry("1350x750+0+0")
welcome.resizable(0, 0)
menu=Menu(welcome,fg='blue')
welcome.config(menu=menu)
filemenu=Menu(menu)
menu.add_cascade(label='Home',menu=filemenu)
filemenu.add_command(label='New')
filemenu.add_command(label='Open')
filemenu.add_separator()
filemenu.add_command(label='Exit',command=welcome.quit)
editmenu=Menu(menu)
menu.add_cascade(label='Edit',menu=(editmenu))
editmenu.add_command(label='Edit')
helpmenu=Menu(menu)
menu.add_cascade(label='Help',menu=helpmenu)
helpmenu.add_command(label='About')
Label(welcome,text="CALCUTATER",font=('arabic',15,)).grid()
equation= StringVar()
Entry(welcome,textvariable=equation).grid()
expression=""
def press(num):
  global expression
  expression=expression+str(num)
  equation.set(expression)
def clear():
  global expression
  expression=""
  equation.set("")
def equalpress():
  global expression
  total=str(eval(expression))
  equation.set(total)
button1=Button(welcome,text='1',fg='black',bg='pink',command=lambda:press(1),height=1,width=4)
button1.grid(row=2,column=0,ipadx=50,ipady=10)
button2=Button(welcome,text='2',fg='black',bg='pink',command=lambda:press(2),height=1,width=4)
button2.grid(row=2,column=1,ipadx=50,ipady=10)
button3=Button(welcome,text='3',fg='black',bg='pink',command=lambda:press(3),height=1,width=4)
button3.grid(row=2,column=2,ipadx=50,ipady=10)
button4=Button(welcome,text='4',fg='black',bg='pink',command=lambda:press(4),height=1,width=4)
button4.grid(row=3,column=0,ipadx=50,ipady=10)
button5=Button(welcome,text='5',fg='black',bg='pink',command=lambda:press(5),height=1,width=4)
button5.grid(row=3,column=1,ipadx=50,ipady=10)
button6=Button(welcome,text='6',fg='black',bg='pink',command=lambda:press(6),height=1,width=4)
button6.grid(row=3,column=2,ipadx=50,ipady=10)
button7=Button(welcome,text='7',fg='black',bg='pink',command=lambda:press(7),height=1,width=4)
button7.grid(row=4,column=0,ipadx=50,ipady=10)
button8=Button(welcome,text='8',fg='black',bg='pink',command=lambda:press(8),height=1,width=4)
button8.grid(row=4,column=1,ipadx=50,ipady=10)
button9=Button(welcome,text='9',fg='black',bg='pink',command=lambda:press(9),height=1,width=4)
button9.grid(row=4,column=2,ipadx=50,ipady=10)
button10=Button(welcome,text='=',fg='black',bg='pink',command=equalpress,height=1,width=4)
button10.grid(row=5,column=0,ipadx=50,ipady=10)
button11=Button(welcome,text='+',fg='black',bg='pink',command=lambda:press("+"),height=1,width=4)
button11.grid(row=2,column=3,ipadx=50,ipady=10)
button12=Button(welcome,text='-',fg='black',bg='pink',command=lambda:press("-"),height=1,width=4)
button12.grid(row=3,column=3,ipadx=50,ipady=10)
button13=Button(welcome,text='*',fg='black',bg='pink',command=lambda:press("*"),height=1,width=4)
button13.grid(row=4,column=3,ipadx=50,ipady=10)
button14=Button(welcome,text='/',fg='black',bg='pink',command=lambda:press("/"),height=1,width=4)
button14.grid(row=5,column=3,ipadx=50,ipady=10)
button15=Button(welcome,text='.',fg='black',bg='pink',command=lambda:press("."),height=1,width=4)
button15.grid(row=5,column=2,ipadx=50,ipady=10)
button16=Button(welcome,text='0',fg='black',bg='pink',command=lambda:press(0),height=1,width=4)
button16.grid(row=5,column=1,ipadx=50,ipady=10)
button17=Button(welcome,text='clear',fg='black',bg='pink',command=clear,height=1,width=4)
button17.grid(row=6,column=1,columnspan=2,ipadx=100,ipady=20)
#r=PhotoImage(file=r"C:\Heena\kr.png")
#button18=Button(welcome,image=r,height=450,width=400)
#button18.grid(row=7,column=1,columnspan=2)
